//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.15 at 07:35:55 ip. EET 
//

package messages.ws.types;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class MessagesListFull extends ArrayList<MessageResponseFull> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public MessagesListFull() {

	}

	public MessagesListFull(List<MessageResponseFull> messages) {
		this.addAll(messages);
	}

	@XmlElement(name = "message")
	public List<MessageResponseFull> getMessages() {
		return this;
	}
}
